
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/it7259/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/include/linux/sched
obj-y	+=  it7259_driver.o
